name: languagetool_textfield
description: The LanguageTool TextField package is a spell-checker designed for Flutter apps. This is useful for apps that need text input like messaging, notes, and email.
version: 1.0.0
homepage: https://github.com/solid-software/languagetool_textfield/


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  async: ^2.11.0
  collection: ^1.17.1
  flutter:
    sdk: flutter
  http: ^1.0.0
  throttling: ^2.0.1
  pointer_interceptor: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.1.2

flutter:
  uses-material-design: true
  assets:
    - images/symbol_boxed_white.png
