name: languagetool_textfield
description: The LanguageTool TextField package is a spell-checker designed for Flutter apps.
version: 0.0.4
homepage: https://github.com/solid-software/languagetool_textfield/


environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  async: ^2.11.0
  collection: ^1.17.1
  flutter:
    sdk: flutter
  http: ^1.0.0
  throttling: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.0.14

flutter:
  uses-material-design: true
  assets:
    - images/symbol_boxed_white.png
