name: languagetool_textfield
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: 1.0.0
  throttling: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  solid_lints: ^0.0.14

flutter:
  uses-material-design: true
