name: Application ON Push & PR DO Code check
on: [push, pull_request]

jobs:
  code-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "pubspec.yaml"

      - name: Setup flutter
        if: steps.check_files.outputs.files_exists == 'true'
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        if: steps.check_files.outputs.files_exists == 'true'
        run: flutter pub get

      - name: Run static code analysis
        if: steps.check_files.outputs.files_exists == 'true'
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true

      - name: Dart Code Metrics
        if: steps.check_files.outputs.files_exists == 'true'
        uses: dart-code-checker/dart-code-metrics-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fatal_warnings: true
          fatal_style: true

      - name: Check formatting
        if: steps.check_files.outputs.files_exists == 'true'
        run: dart format . --set-exit-if-changed

      - name: Run tests
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
          # run tests if `test` folder exists
          if [ -d test ]
          then
              flutter test -r expanded
          else
              echo "Tests not found."
          fi